### ISSUE TITLE
collaboration

### ISSUE THREAD

**Issue by pachadotdev** [paulofelipe/cp2015#2]
Hi!

This just appeared on my github home. Congratulations!!

Long time ago, I found one of your codes to compare a result in fixest vs your 'hack' function vs what I made in base R.

Now I am working in a fixest fork, my idea is to use cpp11 (thinking about the long term), and adding many (600 and counting) tests.

I am also working on d3po, a quite new pkg that takes ideas from the old (but good) d3plus, but also from plotly and other packages.

Let me know if you see any potential collaboration and which is is your consultancy rate.

**Comment by paulofelipe** [comment]
Hi Pacha, it is helpful to know about your ongoing project. Unfortunately, I am busy with other personal projects. Thanks anyway!
